---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

Describe how you have improved as a practitioner and student of data science this quarter through your work in the course. Focus specifically on data science concepts and the skills we employed in learning them. Don't just give a laundry list of topics that you learned (those are in the syllabus, so we know them already). Focus instead on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth. Explain in this essay how this artifact shows growth in the way you are describing.\

I think what I have improved this quarter through my work in the course is the ability to make better looking visualizations and know what will make a visualization clearer. I feel like I have also improved greatly upon how I make my code more readable for a peer. Before this class, I would write code was not very tidy, with variable names that didn't match, has weird organization, and clumped. But now that I have learned more about what the standard is for the tidiness. I am able to change my workflow for the better and be able to better at making my code efficient. I have also gotten alot better at reading documentation and Googling for what I need. I think before, I struggled alot with understand how basic functions worked and how to do complex coding tasks; but through my experiences in this class, I feel much better at finding resources to figure out solutions to my problems. I showed demonstration of this in my avocado lab where I had to use alot of documentation to figure out what some of the functions did and I felt like I have gotten better at reading/picking up information I need. I have also improved my skill of decipher what kind of graph I need to make in order to make conclusions on the data. This is shown in my graph from my trout lab. I also became better at manipulating data frames in a way where it made it easier to analysis on such as using joins, pivots, filters, mutates, and summaries. Not only did I learn about how to use many of the functions in r effectively, but I also picked up a lot of skills that would aid in my explorations of data science.
