---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we've said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term "efficiency" means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Include: What is the definition of "efficiency"? What does efficiency look like in statistical computing / data science? What does efficiency allow you to do? Why is efficiency important? Where did you encounter efficiency, and what were some ["a-ha" moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

The term efficiency refers the how quick/how energy saving it was to complete a task. Efficiency in statistical computing is the ability to write concise and non repeated code that does the job well. It would also utilize the most modern tools. Efficiency allows you to save time computing and most of the time allows other users to understand your code easier. Efficiency is important because when you work in industry on a database of millions of entries, every millisecond you can save parsing each entry can decrease the program run time by even days. I encountered efficiency through the use of the across function and creation of my own functions. The across function is very efficient because it cuts the cost of having repeated code and will do the work of multiple function calls in one. Some a-ha moments of efficiency was when i realized that I could mutate multiple items with just one mutate function call and before this, I thought I had to use different mutate functions for different items. Another a-ha moment was when I realized that making tidier code like indenting when i am supposed to makes me more efficient. This is because when I did not have my code tidy, it was time consuming to debug large clumps of code and made it difficult to spot the errors. Therefore, I started to make my code alot more tidier starting lab 5 since it was more time efficient in the long run. These were my experiences with efficiency in this class.
