---
title: "challenge9"
author: "Jia Jiang"
format: 
  html:
    self-contained: true
    code-tools: true
    code-fold: true
execute: 
  eval: true
  error: false
  echo: true
  messages: false
  warning: false
editor: visual
---

```{r}
library(tidyverse)
library(broom)
library(gt)
baby_data <- read_csv("StateNames_a.csv")
```

```{r}
table3 <- baby_data |>
    filter(Name %in% c("Allan", "Alan", "Allen"), 
         Year == 2000, 
         State %in% c("CA", "PA"),
         Gender == "M") |>
  group_by(State, Name) |>
  summarise(Total = sum(Count)) |>
  mutate(prop = Total/sum(Total)) |>
  select(State, Name, prop) |>
  pivot_wider(values_from = prop, 
              values_fill = 0,
              names_from = Name)  |>
  ungroup()
```

```{r}
table3 |>
  gt() |>
  cols_label(
    State = md("**State**"),
    Alan = md("**Alan**"),
    Allan = md("**Allan**"),
    Allen = md("**Allen**")) |>
  fmt_percent(columns = 2:4, 
              decimals = 1) |>
  tab_header(title = "Percentages of `Alan` Names", 
             subtitle = "by State") |>
  tab_spanner(columns = 2:4, 
              label = "Names") |>
  tab_source_note( source_note=md("From [Dropbox Link](https://www.dropbox.com/sh/czm61yzmvzl6xfb/AABEFdpy02aNRhZ_vcxrVAQSa?dl=0)")) |>
  data_color(columns = State, 
             colors = c("red", "blue")) |>
  tab_style(locations= cells_body(columns = 2:4), 
            style = list(cell_text(font = "Comic Sansa",
                                   style = "italic")))
```

```{r}
table1 <- baby_data |>
  filter(Name == "Allison") |>
  group_by(Gender, State) |>
  summarise(Total = sum(Count)) |>
  pivot_wider(values_from = Total, 
              values_fill = 0,
              names_from = Gender)
```

```{r}
table1 |>
  gt() |>
  tab_header(title = "Count of `Allisons`", 
             subtitle = "by State") |>
  tab_spanner(columns = 2:3, 
              label = "Gender") |>
  cols_label(
    F = "Female",
    M = "Male"
  )
  
```

```{r}
table2 <- baby_data |>
  filter(Name %in% c("Allan", "Alan", "Allen"), 
         Year == 2000, 
         State %in% c("CA", "PA"),
         Gender == "M") |>
  group_by(State, Name) |>
  summarise(Total = sum(Count)) |>
  pivot_wider(values_from = Total, 
              values_fill = 0,
              names_from = Name) |>
  ungroup()

```

```{r}
table2 |>
  gt() |>
  tab_stubhead("State") |>
  tab_header(title = "Count of `Alan` Names", 
             subtitle = "by State")
```
